// <auto-generated />
namespace OperationVanguard.Core;

internal static partial class RegistryPayloads
{
    internal const string AttachmentsJson = """""
[
  {
    "id": "muzzle_flash_hider",
    "name": "消焰器",
    "slot": 0,
    "description": "向側面排氣，消除連發中晃瞎自己的槍口火光。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.94,
      "drawTime": 1.04,
      "damageRangeScale": 0.97
    },
    "unlockLevel": 1,
    "pros": [
      "垂直後座力降低",
      "槍口火光不再糊住自己的視線"
    ],
    "cons": [
      "舉槍速度較慢",
      "傷害射程微幅縮短"
    ]
  },
  {
    "id": "muzzle_compensator",
    "name": "補償器",
    "slot": 0,
    "description": "頂部開孔，壓制水平飄移，代價是腰射散佈變大。",
    "classes": [],
    "mods": {
      "recoilYaw": 0.78,
      "recoilPitch": 0.92,
      "hipSpread": 1.08,
      "adsTime": 1.03
    },
    "unlockLevel": 5,
    "pros": [
      "水平後座力大幅收斂",
      "垂直後座力略微降低"
    ],
    "cons": [
      "腰射散佈變大",
      "瞄準速度較慢"
    ]
  },
  {
    "id": "muzzle_brake",
    "name": "槍口制退器",
    "slot": 0,
    "description": "側向大開孔壓平上跳，但把槍甩向側邊。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.82,
      "recoilYaw": 1.12,
      "hipSpread": 1.1
    },
    "unlockLevel": 8,
    "pros": [
      "垂直後座力顯著降低"
    ],
    "cons": [
      "水平後座力變差",
      "腰射散佈變大"
    ]
  },
  {
    "id": "muzzle_choke",
    "name": "霰彈槍縮口",
    "slot": 0,
    "description": "把彈丸擴散收攏成近似獨頭彈的一束。",
    "classes": [
      "shotgun"
    ],
    "mods": {
      "hipSpread": 0.72,
      "adsSpread": 0.7,
      "adsTime": 1.15,
      "drawTime": 1.08
    },
    "unlockLevel": 6,
    "pros": [
      "彈丸散佈大幅收攏"
    ],
    "cons": [
      "瞄準速度慢很多",
      "舉槍速度較慢"
    ]
  },
  {
    "id": "muzzle_suppressor",
    "name": "消音器",
    "slot": 0,
    "description": "讓你不出現在小地圖上。洩掉膛壓，射程也跟著洩掉。",
    "classes": [],
    "mods": {
      "suppressed": true,
      "hidesMinimapDot": true,
      "damageRangeScale": 0.9,
      "adsTime": 1.05,
      "muzzleVelocity": 0.95
    },
    "unlockLevel": 3,
    "pros": [
      "消音",
      "開火時不顯示小地圖光點"
    ],
    "cons": [
      "傷害射程縮短",
      "瞄準速度較慢",
      "槍口初速降低"
    ]
  },
  {
    "id": "muzzle_monolithic_suppressor",
    "name": "整體式消音器",
    "slot": 0,
    "description": "全長筒身兼作槍管延長——安靜，而且打得更遠。",
    "classes": [],
    "mods": {
      "suppressed": true,
      "hidesMinimapDot": true,
      "damageRangeScale": 1.05,
      "recoilPitch": 0.95,
      "adsTime": 1.12,
      "drawTime": 1.1,
      "movementSpeed": 0.98
    },
    "unlockLevel": 12,
    "pros": [
      "消音",
      "開火時不顯示小地圖光點",
      "傷害射程延長"
    ],
    "cons": [
      "瞄準速度慢很多",
      "舉槍速度較慢",
      "移動速度較慢"
    ]
  },
  {
    "id": "muzzle_light_suppressor",
    "name": "輕量消音器",
    "slot": 0,
    "description": "為進攻調校的鈦合金筒身：操控性保住了，彈道付出代價。",
    "classes": [],
    "mods": {
      "suppressed": true,
      "hidesMinimapDot": true,
      "adsTime": 0.98,
      "damageRangeScale": 0.86,
      "muzzleVelocity": 0.9,
      "sprintOutTime": 1.05
    },
    "unlockLevel": 20,
    "pros": [
      "消音",
      "開火時不顯示小地圖光點",
      "瞄準速度更快"
    ],
    "cons": [
      "傷害射程大幅縮減",
      "槍口初速偏低",
      "衝刺後開火較慢"
    ]
  },
  {
    "id": "barrel_long_heavy",
    "name": "加長重型槍管",
    "slot": 1,
    "description": "多一公分膛線就多一分初速，操控性照付。",
    "classes": [],
    "mods": {
      "damageRangeScale": 1.2,
      "muzzleVelocity": 1.25,
      "recoilPitch": 0.95,
      "adsTime": 1.12,
      "movementSpeed": 0.95,
      "swayAmount": 1.15
    },
    "unlockLevel": 9,
    "pros": [
      "傷害射程大幅延長",
      "槍口初速大幅提高"
    ],
    "cons": [
      "瞄準速度較慢",
      "移動速度較慢",
      "瞄準晃動增加"
    ]
  },
  {
    "id": "barrel_short_cqb",
    "name": "CQB短管",
    "slot": 1,
    "description": "為走廊近戰砍到剩導氣座。",
    "classes": [],
    "mods": {
      "adsTime": 0.88,
      "movementSpeed": 1.04,
      "hipSpread": 0.9,
      "damageRangeScale": 0.85,
      "recoilPitch": 1.12
    },
    "unlockLevel": 4,
    "pros": [
      "瞄準速度更快",
      "移動速度更快",
      "腰射更集中"
    ],
    "cons": [
      "傷害射程大幅縮短",
      "垂直後座力增加"
    ]
  },
  {
    "id": "barrel_reinforced",
    "name": "強化重型槍管",
    "slot": 1,
    "description": "厚壁鍍鉻內膛；子彈穿過掩體仍保有動能。",
    "classes": [],
    "mods": {
      "penetration": 1.35,
      "damageRangeScale": 1.08,
      "adsTime": 1.1,
      "sprintOutTime": 1.08,
      "movementSpeed": 0.96
    },
    "unlockLevel": 15,
    "pros": [
      "穿牆能力遠勝以往",
      "傷害射程延長"
    ],
    "cons": [
      "瞄準速度較慢",
      "衝刺後開火較慢",
      "移動速度較慢"
    ]
  },
  {
    "id": "barrel_fluted",
    "name": "開槽槍管",
    "slot": 1,
    "description": "車出來的凹槽削掉了前端重量。",
    "classes": [],
    "mods": {
      "adsTime": 0.94,
      "drawTime": 0.9,
      "recoilPitch": 1.08,
      "damageRangeScale": 0.95
    },
    "unlockLevel": 11,
    "pros": [
      "瞄準速度更快",
      "舉槍速度更快"
    ],
    "cons": [
      "垂直後座力增加",
      "傷害射程略微縮短"
    ]
  },
  {
    "id": "barrel_ported",
    "name": "開孔槍管",
    "slot": 1,
    "description": "槍口前方的洩氣孔卸掉膛壓，把槍壓穩。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.88,
      "recoilYaw": 0.9,
      "damageRangeScale": 0.92,
      "hipSpread": 1.06
    },
    "unlockLevel": 7,
    "pros": [
      "雙軸後座力降低"
    ],
    "cons": [
      "傷害射程縮短",
      "腰射散佈變大"
    ]
  },
  {
    "id": "barrel_marksman",
    "name": "神射手槍管",
    "slot": 1,
    "description": "競賽級管身，給願意慢慢來的人。",
    "classes": [],
    "mods": {
      "adsSpread": 0.8,
      "swayAmount": 0.85,
      "damageRangeScale": 1.12,
      "adsTime": 1.15,
      "movementSpeed": 0.94
    },
    "unlockLevel": 18,
    "pros": [
      "瞄準精準度大幅提升",
      "瞄準晃動減少",
      "傷害射程延長"
    ],
    "cons": [
      "瞄準速度慢很多",
      "移動速度較慢"
    ]
  },
  {
    "id": "barrel_lancer",
    "name": "騎兵長槍槍管",
    "slot": 1,
    "description": "為邊跑邊打削到極簡；精準度不是重點。",
    "classes": [
      "smg",
      "shotgun"
    ],
    "mods": {
      "movementSpeed": 1.06,
      "sprintOutTime": 0.85,
      "damageRangeScale": 0.8,
      "adsSpread": 1.2
    },
    "unlockLevel": 22,
    "pros": [
      "移動速度更快",
      "衝刺後開火快很多"
    ],
    "cons": [
      "傷害射程大幅縮減",
      "瞄準精準度大幅變差"
    ]
  },
  {
    "id": "optic_reflex_micro",
    "name": "微型反射瞄具",
    "slot": 2,
    "description": "能越過機械瞄具的最小光點。",
    "classes": [],
    "mods": {
      "swayAmount": 0.97,
      "adsZoomAdd": 0.05,
      "adsTime": 1.02
    },
    "unlockLevel": 2,
    "pros": [
      "視野乾淨",
      "晃動略微減少"
    ],
    "cons": [
      "瞄準速度微幅變慢"
    ]
  },
  {
    "id": "optic_red_dot",
    "name": "紅點瞄準鏡",
    "slot": 2,
    "description": "制式紅點。精準、單純，就是有點笨重。",
    "classes": [],
    "mods": {
      "adsSpread": 0.95,
      "adsZoomAdd": 0.1,
      "adsTime": 1.04
    },
    "unlockLevel": 4,
    "pros": [
      "瞄準精準度提升",
      "準星簡潔不擋視線"
    ],
    "cons": [
      "瞄準速度較慢"
    ]
  },
  {
    "id": "optic_holographic",
    "name": "全像瞄準鏡",
    "slot": 2,
    "description": "大視窗、環形準星，還有一個掛在導軌上感覺得到的殼。",
    "classes": [],
    "mods": {
      "swayAmount": 0.95,
      "adsZoomAdd": 0.15,
      "adsTime": 1.06,
      "hipSpread": 1.05
    },
    "unlockLevel": 8,
    "pros": [
      "視野寬廣",
      "瞄準晃動減少"
    ],
    "cons": [
      "瞄準速度較慢",
      "腰射散佈變大"
    ]
  },
  {
    "id": "optic_offset_canted",
    "name": "側傾偏置瞄具",
    "slot": 2,
    "description": "側轉45度就能接上的光點——快，但放棄了精細準星。",
    "classes": [],
    "mods": {
      "adsTime": 0.96,
      "adsZoomAdd": -0.1,
      "adsSpread": 1.08,
      "hipSpread": 1.04
    },
    "unlockLevel": 14,
    "pros": [
      "瞄準速度更快",
      "周邊視野更廣"
    ],
    "cons": [
      "瞄準精準度變差",
      "放大倍率降低",
      "腰射略微變大"
    ]
  },
  {
    "id": "optic_scope_3x",
    "name": "3x戰鬥瞄準鏡",
    "slot": 2,
    "description": "帶人字準星的中距離鏡片；第一款近距離會反咬你的瞄具。",
    "classes": [],
    "mods": {
      "adsZoomAdd": 0.6,
      "adsSpread": 0.9,
      "adsTime": 1.12,
      "hipSpread": 1.15,
      "movementSpeed": 0.98
    },
    "unlockLevel": 13,
    "pros": [
      "倍率充足",
      "瞄準精準度提升"
    ],
    "cons": [
      "瞄準速度較慢",
      "腰射散佈大幅變大",
      "移動速度較慢"
    ]
  },
  {
    "id": "optic_scope_4x",
    "name": "4x戰術瞄準鏡",
    "slot": 2,
    "description": "用來鎖線的長焦鏡片。你的麻煩會從後座力變成晃動。",
    "classes": [],
    "mods": {
      "adsZoomAdd": 1,
      "adsSpread": 0.85,
      "adsTime": 1.18,
      "swayAmount": 1.2,
      "hipSpread": 1.2
    },
    "unlockLevel": 17,
    "pros": [
      "高倍率",
      "瞄準精準度大幅提升"
    ],
    "cons": [
      "瞄準速度慢很多",
      "瞄準晃動增加",
      "腰射散佈大幅變大"
    ]
  },
  {
    "id": "optic_thermal",
    "name": "熱像複合瞄具",
    "slot": 2,
    "description": "隔著煙霧把人體標成白色。開機慢，也重。",
    "classes": [],
    "mods": {
      "adsZoomAdd": 0.5,
      "adsSpread": 0.88,
      "adsTime": 1.22,
      "drawTime": 1.15,
      "hipSpread": 1.1
    },
    "unlockLevel": 24,
    "pros": [
      "隔著煙霧標示目標",
      "瞄準精準度提升"
    ],
    "cons": [
      "瞄準速度極慢",
      "舉槍速度慢",
      "腰射散佈變大"
    ]
  },
  {
    "id": "optic_variable_sniper",
    "name": "可變倍狙擊鏡",
    "slot": 2,
    "description": "把倍率轉到底，用在多數玩家從不嘗試的一槍。",
    "classes": [
      "sniper",
      "marksman"
    ],
    "mods": {
      "adsZoomAdd": 2,
      "adsSpread": 0.7,
      "adsTime": 1.25,
      "swayAmount": 1.25,
      "movementSpeed": 0.96
    },
    "unlockLevel": 26,
    "pros": [
      "極高倍率",
      "瞄準精準度近乎完美"
    ],
    "cons": [
      "瞄準速度極慢",
      "鏡體晃動嚴重",
      "移動速度較慢"
    ]
  },
  {
    "id": "under_vertical_grip",
    "name": "垂直前握把",
    "slot": 3,
    "description": "持續射擊時把槍口往下壓。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.85,
      "adsTime": 1.06,
      "movementSpeed": 0.98
    },
    "unlockLevel": 3,
    "pros": [
      "垂直後座力顯著降低"
    ],
    "cons": [
      "瞄準速度較慢",
      "移動速度較慢"
    ]
  },
  {
    "id": "under_angled_grip",
    "name": "傾斜前握把",
    "slot": 3,
    "description": "手腕前傾，衝刺結束後舉槍更快。",
    "classes": [],
    "mods": {
      "adsTime": 0.9,
      "sprintOutTime": 0.88,
      "recoilPitch": 1.08,
      "hipSpread": 1.05
    },
    "unlockLevel": 6,
    "pros": [
      "瞄準速度更快",
      "衝刺後開火更快"
    ],
    "cons": [
      "垂直後座力增加",
      "腰射散佈變大"
    ]
  },
  {
    "id": "under_bipod",
    "name": "摺疊腳架",
    "slot": 3,
    "description": "前端配重殺掉後座與晃動；順便殺掉你的腳程。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.8,
      "swayAmount": 0.8,
      "movementSpeed": 0.94,
      "adsTime": 1.08
    },
    "unlockLevel": 10,
    "pros": [
      "垂直後座力大幅降低",
      "瞄準晃動明顯減少"
    ],
    "cons": [
      "移動速度慢很多",
      "瞄準速度較慢"
    ]
  },
  {
    "id": "under_ranger_grip",
    "name": "遊騎兵護木",
    "slot": 3,
    "description": "為腰射而生，後果自負。",
    "classes": [],
    "mods": {
      "hipSpread": 0.82,
      "adsSpread": 1.12,
      "adsTime": 1.05
    },
    "unlockLevel": 12,
    "pros": [
      "腰射散佈大幅收攏"
    ],
    "cons": [
      "瞄準精準度變差",
      "瞄準速度較慢"
    ]
  },
  {
    "id": "under_handstop",
    "name": "聚合物手擋",
    "slot": 3,
    "description": "一個拇指擋塊，沒別的。機動優先。",
    "classes": [],
    "mods": {
      "sprintOutTime": 0.85,
      "movementSpeed": 1.03,
      "recoilYaw": 1.1,
      "hipSpread": 1.06
    },
    "unlockLevel": 8,
    "pros": [
      "衝刺後開火快很多",
      "移動速度更快"
    ],
    "cons": [
      "水平後座力增加",
      "腰射散佈變大"
    ]
  },
  {
    "id": "under_damped_grip",
    "name": "阻尼前握把",
    "slot": 3,
    "description": "鎢芯握把，吸收雙軸的後座衝擊。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.88,
      "recoilYaw": 0.88,
      "adsTime": 1.1,
      "drawTime": 1.08,
      "movementSpeed": 0.97
    },
    "unlockLevel": 16,
    "pros": [
      "雙軸後座力降低"
    ],
    "cons": [
      "瞄準速度較慢",
      "舉槍速度較慢",
      "移動速度較慢"
    ]
  },
  {
    "id": "under_grenade_launcher",
    "name": "40mm榴彈發射器",
    "slot": 3,
    "description": "護木下掛一發40mm榴彈。其餘一切都變慢。",
    "classes": [
      "assault_rifle",
      "lmg"
    ],
    "mods": {
      "recoilPitch": 0.95,
      "adsTime": 1.15,
      "movementSpeed": 0.93,
      "drawTime": 1.12,
      "sprintOutTime": 1.1
    },
    "unlockLevel": 21,
    "pros": [
      "槍管下掛爆裂彈",
      "額外配重穩住槍口"
    ],
    "cons": [
      "瞄準速度慢很多",
      "移動速度慢很多",
      "舉槍遲鈍"
    ]
  },
  {
    "id": "mag_extended",
    "name": "加長彈匣",
    "slot": 4,
    "description": "多十發，才需要開始想換彈匣的事。",
    "classes": [],
    "mods": {
      "magSizeAdd": 10,
      "reloadTime": 1.08,
      "adsTime": 1.04,
      "movementSpeed": 0.99
    },
    "unlockLevel": 2,
    "pros": [
      "+10發"
    ],
    "cons": [
      "裝填較慢",
      "瞄準速度較慢"
    ]
  },
  {
    "id": "mag_extended_large",
    "name": "高容量彈匣",
    "slot": 4,
    "description": "多掛三十發的重量。",
    "classes": [],
    "mods": {
      "magSizeAdd": 30,
      "reloadTime": 1.25,
      "adsTime": 1.12,
      "movementSpeed": 0.96,
      "sprintOutTime": 1.08
    },
    "unlockLevel": 9,
    "pros": [
      "+30發"
    ],
    "cons": [
      "裝填慢很多",
      "瞄準速度較慢",
      "移動速度較慢"
    ]
  },
  {
    "id": "mag_drum",
    "name": "彈鼓",
    "slot": 4,
    "description": "多六十發。你哪裡都衝刺不了。",
    "classes": [],
    "mods": {
      "magSizeAdd": 60,
      "reloadTime": 1.45,
      "adsTime": 1.2,
      "movementSpeed": 0.92,
      "drawTime": 1.2
    },
    "unlockLevel": 18,
    "pros": [
      "+60發"
    ],
    "cons": [
      "裝填極慢",
      "瞄準速度極慢",
      "移動速度慢很多"
    ]
  },
  {
    "id": "mag_taped",
    "name": "併聯彈匣",
    "slot": 4,
    "description": "兩個彈匣用膠帶綁在一起——全遊戲最快的裝填。",
    "classes": [],
    "mods": {
      "reloadTime": 0.72,
      "magSizeAdd": -2,
      "adsTime": 1.05
    },
    "unlockLevel": 5,
    "pros": [
      "裝填速度大幅提升"
    ],
    "cons": [
      "-2發",
      "瞄準速度較慢"
    ]
  },
  {
    "id": "mag_lightweight",
    "name": "輕量彈匣",
    "slot": 4,
    "description": "短版聚合物彈匣，什麼都不擋。",
    "classes": [],
    "mods": {
      "adsTime": 0.94,
      "movementSpeed": 1.03,
      "reloadTime": 0.92,
      "magSizeAdd": -5
    },
    "unlockLevel": 7,
    "pros": [
      "瞄準速度更快",
      "移動速度更快",
      "裝填更快"
    ],
    "cons": [
      "-5發"
    ]
  },
  {
    "id": "mag_armor_piercing",
    "name": "穿甲彈",
    "slot": 4,
    "description": "硬化彈芯，合板對它只是有點礙事。",
    "classes": [],
    "mods": {
      "penetration": 1.6,
      "damageRangeScale": 1.05,
      "reloadTime": 1.1,
      "muzzleVelocity": 0.95,
      "magSizeAdd": -4
    },
    "unlockLevel": 14,
    "pros": [
      "穿牆能力大幅提升",
      "傷害射程略微延長"
    ],
    "cons": [
      "-4發",
      "裝填較慢",
      "槍口初速降低"
    ]
  },
  {
    "id": "mag_subsonic",
    "name": "次音速彈",
    "slot": 4,
    "description": "沒有音爆聲，小地圖上就沒有光點——射程也一起沒了。",
    "classes": [],
    "mods": {
      "hidesMinimapDot": true,
      "recoilPitch": 0.95,
      "muzzleVelocity": 0.7,
      "damageRangeScale": 0.85
    },
    "unlockLevel": 20,
    "pros": [
      "開火時不顯示小地圖光點",
      "後座力略微變軟"
    ],
    "cons": [
      "槍口初速大幅降低",
      "傷害射程縮減"
    ]
  },
  {
    "id": "mag_overpressured",
    "name": "超壓彈",
    "slot": 4,
    "description": "高裝藥，打得更遠，順便想把你的手腕一起帶走。",
    "classes": [],
    "mods": {
      "muzzleVelocity": 1.3,
      "damageRangeScale": 1.18,
      "recoilPitch": 1.2,
      "recoilYaw": 1.15,
      "magSizeAdd": -4
    },
    "unlockLevel": 25,
    "pros": [
      "槍口初速大幅提高",
      "傷害射程延長"
    ],
    "cons": [
      "-4發",
      "雙軸後座力大增"
    ]
  },
  {
    "id": "stock_heavy",
    "name": "重型槍托",
    "slot": 5,
    "description": "抵肩像架在射擊台上，移動起來也像。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.85,
      "swayAmount": 0.8,
      "adsTime": 1.1,
      "movementSpeed": 0.95,
      "sprintOutTime": 1.1
    },
    "unlockLevel": 5,
    "pros": [
      "垂直後座力顯著降低",
      "瞄準晃動明顯減少"
    ],
    "cons": [
      "瞄準速度較慢",
      "移動速度較慢",
      "衝刺後開火較慢"
    ]
  },
  {
    "id": "stock_skeleton",
    "name": "骨架槍托",
    "slot": 5,
    "description": "銑到只剩下貼腮的部分。",
    "classes": [],
    "mods": {
      "adsTime": 0.9,
      "movementSpeed": 1.05,
      "sprintOutTime": 0.9,
      "recoilPitch": 1.15,
      "adsSpread": 1.08
    },
    "unlockLevel": 3,
    "pros": [
      "瞄準速度更快",
      "移動速度更快",
      "衝刺後開火更快"
    ],
    "cons": [
      "垂直後座力增加",
      "瞄準精準度變差"
    ]
  },
  {
    "id": "stock_none",
    "name": "無槍托",
    "slot": 5,
    "description": "完全沒有槍托。純粹進攻，零穩定性。",
    "classes": [],
    "mods": {
      "movementSpeed": 1.08,
      "adsTime": 0.85,
      "sprintOutTime": 0.8,
      "recoilPitch": 1.25,
      "recoilYaw": 1.2,
      "adsSpread": 1.15,
      "swayAmount": 1.2
    },
    "unlockLevel": 11,
    "pros": [
      "瞄準速度快很多",
      "移動速度快很多",
      "衝刺後幾乎立即開火"
    ],
    "cons": [
      "雙軸後座力極大",
      "瞄準精準度低落",
      "瞄準晃動嚴重"
    ]
  },
  {
    "id": "stock_collapsible",
    "name": "伸縮槍托",
    "slot": 5,
    "description": "折衷的伸縮槍托，給下不了決心的人。",
    "classes": [],
    "mods": {
      "movementSpeed": 1.03,
      "adsTime": 0.95,
      "recoilYaw": 1.08,
      "swayAmount": 1.06
    },
    "unlockLevel": 6,
    "pros": [
      "移動速度更快",
      "瞄準速度更快"
    ],
    "cons": [
      "水平後座力增加",
      "瞄準晃動增加"
    ]
  },
  {
    "id": "stock_precision",
    "name": "精準槍托",
    "slot": 5,
    "description": "可調托背與貼腮墊；整支就為了把準星定住。",
    "classes": [],
    "mods": {
      "swayAmount": 0.7,
      "adsSpread": 0.88,
      "adsTime": 1.08,
      "movementSpeed": 0.96,
      "drawTime": 1.05
    },
    "unlockLevel": 15,
    "pros": [
      "瞄準晃動大幅減少",
      "瞄準精準度提升"
    ],
    "cons": [
      "瞄準速度較慢",
      "移動速度較慢",
      "舉槍速度較慢"
    ]
  },
  {
    "id": "stock_padded",
    "name": "緩衝墊槍托",
    "slot": 5,
    "description": "厚橡膠墊，吃掉各個方向的衝量。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.9,
      "recoilYaw": 0.9,
      "movementSpeed": 0.97,
      "adsTime": 1.05
    },
    "unlockLevel": 9,
    "pros": [
      "雙軸後座力降低"
    ],
    "cons": [
      "移動速度較慢",
      "瞄準速度較慢"
    ]
  },
  {
    "id": "stock_brace",
    "name": "輔助瞄準支架",
    "slot": 5,
    "description": "靠背帶張力繃緊的支架，讓你瞄準時還能繼續走。",
    "classes": [],
    "mods": {
      "adsSpeed": 1.15,
      "swayAmount": 0.9,
      "adsTime": 1.06,
      "sprintOutTime": 1.05
    },
    "unlockLevel": 19,
    "pros": [
      "瞄準時移動快很多",
      "瞄準晃動減少"
    ],
    "cons": [
      "瞄準速度較慢",
      "衝刺後開火較慢"
    ]
  },
  {
    "id": "grip_rubberized",
    "name": "橡膠握把",
    "slot": 6,
    "description": "軟質包膠，吸掉每次連發的第一槍。",
    "classes": [],
    "mods": {
      "recoilPitch": 0.9,
      "adsTime": 1.05
    },
    "unlockLevel": 2,
    "pros": [
      "垂直後座力降低"
    ],
    "cons": [
      "瞄準速度較慢"
    ]
  },
  {
    "id": "grip_stippled",
    "name": "顆粒握把膠帶",
    "slot": 6,
    "description": "粗糙膠帶，甩槍上目標時槍身不會滑動。",
    "classes": [],
    "mods": {
      "adsTime": 0.9,
      "sprintOutTime": 0.9,
      "recoilPitch": 1.1
    },
    "unlockLevel": 4,
    "pros": [
      "瞄準速度更快",
      "衝刺後開火更快"
    ],
    "cons": [
      "垂直後座力增加"
    ]
  },
  {
    "id": "grip_granulated",
    "name": "粗砂握把",
    "slot": 6,
    "description": "噴砂面板，應付濕手與快速換彈匣。",
    "classes": [],
    "mods": {
      "drawTime": 0.85,
      "reloadTime": 0.9,
      "recoilYaw": 1.1,
      "hipSpread": 1.05
    },
    "unlockLevel": 7,
    "pros": [
      "舉槍速度快很多",
      "裝填更快"
    ],
    "cons": [
      "水平後座力增加",
      "腰射散佈變大"
    ]
  },
  {
    "id": "grip_quickdraw",
    "name": "快拔握把",
    "slot": 6,
    "description": "削短的握把尾，出槍套時沒人聽得見。",
    "classes": [],
    "mods": {
      "drawTime": 0.75,
      "swayAmount": 1.15,
      "adsSpread": 1.05
    },
    "unlockLevel": 10,
    "pros": [
      "舉槍速度大幅提升"
    ],
    "cons": [
      "瞄準晃動增加",
      "瞄準精準度變差"
    ]
  },
  {
    "id": "grip_ergonomic",
    "name": "人體工學握把",
    "slot": 6,
    "description": "掌心隆起加上更大傾角——穩，但彈匣井操作變慢。",
    "classes": [],
    "mods": {
      "swayAmount": 0.85,
      "adsSpeed": 1.08,
      "reloadTime": 1.08,
      "movementSpeed": 0.98
    },
    "unlockLevel": 16,
    "pros": [
      "瞄準晃動減少",
      "瞄準時移動更快"
    ],
    "cons": [
      "裝填較慢",
      "移動速度較慢"
    ]
  },
  {
    "id": "grip_heavy_wrap",
    "name": "加重纏繩握把",
    "slot": 6,
    "description": "加重傘繩纏繞，止住槍身橫向飄移。",
    "classes": [],
    "mods": {
      "recoilYaw": 0.85,
      "hipSpread": 0.95,
      "drawTime": 1.12,
      "adsTime": 1.06
    },
    "unlockLevel": 13,
    "pros": [
      "水平後座力顯著降低",
      "腰射更集中"
    ],
    "cons": [
      "舉槍速度較慢",
      "瞄準速度較慢"
    ]
  },
  {
    "id": "laser_1mw",
    "name": "1mW雷射",
    "slot": 7,
    "description": "牆上一顆暗淡的光點，讓腰射變得誠實。",
    "classes": [],
    "mods": {
      "hipSpread": 0.78,
      "adsTime": 1.04,
      "movementSpeed": 0.99
    },
    "unlockLevel": 1,
    "pros": [
      "腰射散佈大幅收攏"
    ],
    "cons": [
      "瞄準速度較慢",
      "光束會被敵人看見"
    ]
  },
  {
    "id": "laser_5mw",
    "name": "5mW雷射",
    "slot": 7,
    "description": "亮到白天也看得見。亮到他們也看得見。",
    "classes": [],
    "mods": {
      "hipSpread": 0.68,
      "adsTime": 0.95,
      "movementSpeed": 0.97,
      "drawTime": 1.06
    },
    "unlockLevel": 6,
    "pros": [
      "腰射大幅收攏",
      "瞄準速度更快"
    ],
    "cons": [
      "移動速度較慢",
      "舉槍速度較慢",
      "光束極為顯眼"
    ]
  },
  {
    "id": "laser_ir",
    "name": "紅外線照明器",
    "slot": 7,
    "description": "肉眼看不見，沒人能循著光束找到你。",
    "classes": [],
    "mods": {
      "hipSpread": 0.85,
      "sprintOutTime": 0.9,
      "drawTime": 1.1,
      "adsTime": 1.05
    },
    "unlockLevel": 12,
    "pros": [
      "腰射更集中",
      "衝刺後開火更快",
      "敵人看不見光束"
    ],
    "cons": [
      "舉槍速度較慢",
      "瞄準速度較慢"
    ]
  },
  {
    "id": "laser_steady",
    "name": "穩瞄雷射",
    "slot": 7,
    "description": "陀螺穩定模組，抑制高倍率下的抖動。",
    "classes": [],
    "mods": {
      "swayAmount": 0.75,
      "hipSpread": 0.9,
      "adsTime": 1.08,
      "movementSpeed": 0.97
    },
    "unlockLevel": 17,
    "pros": [
      "瞄準晃動明顯減少",
      "腰射更集中"
    ],
    "cons": [
      "瞄準速度較慢",
      "移動速度較慢"
    ]
  },
  {
    "id": "laser_rangefinder",
    "name": "雷射測距儀",
    "slot": 7,
    "description": "替你測距，並修掉彈道補正的誤差。",
    "classes": [],
    "mods": {
      "damageRangeScale": 1.1,
      "adsSpread": 0.92,
      "adsTime": 1.1,
      "drawTime": 1.08
    },
    "unlockLevel": 23,
    "pros": [
      "傷害射程延長",
      "瞄準精準度提升"
    ],
    "cons": [
      "瞄準速度較慢",
      "舉槍速度較慢"
    ]
  },
  {
    "id": "laser_combat_light",
    "name": "戰術槍燈",
    "slot": 7,
    "description": "槍燈與雷射合在同一個殼裡。室內好用，室外找死。",
    "classes": [],
    "mods": {
      "hipSpread": 0.72,
      "sprintOutTime": 0.92,
      "adsSpread": 1.1,
      "movementSpeed": 0.98
    },
    "unlockLevel": 9,
    "pros": [
      "腰射散佈極為集中",
      "衝刺後開火更快"
    ],
    "cons": [
      "瞄準精準度變差",
      "移動速度較慢",
      "等於幫所有人照亮你"
    ]
  }
]
""""";
}
