// <auto-generated />
namespace OperationVanguard.Core;

internal static partial class RegistryPayloads
{
    internal const string EquipmentJson = """""
[
  {
    "id": "frag",
    "name": "破片手榴彈",
    "slot": "lethal",
    "description": "可延遲投擲的破片手榴彈。其餘致命裝備都以它為衡量基準。",
    "count": 1,
    "unlockLevel": 0,
    "projectileKind": 0,
    "damage": 130,
    "radius": 5.5,
    "fuse": 3.5,
    "throwSpeed": 16
  },
  {
    "id": "semtex",
    "name": "Semtex",
    "slot": "lethal",
    "description": "碰到什麼就黏什麼。引信更短、爆幅更集中，也沒辦法彈牆繞角。",
    "count": 1,
    "unlockLevel": 4,
    "projectileKind": 1,
    "damage": 140,
    "radius": 4.6,
    "fuse": 2.2,
    "throwSpeed": 18
  },
  {
    "id": "throwing_knife",
    "name": "投擲刀",
    "slot": "lethal",
    "description": "無聲，乾淨命中即致命，還能從屍體上撿回。",
    "count": 1,
    "unlockLevel": 7,
    "projectileKind": 11,
    "damage": 200,
    "radius": 0,
    "fuse": 0,
    "throwSpeed": 32
  },
  {
    "id": "c4",
    "name": "C4",
    "slot": "lethal",
    "description": "遙控炸藥，由你自己決定引爆時機。",
    "count": 1,
    "unlockLevel": 10,
    "projectileKind": 9,
    "deployableKind": 2,
    "damage": 190,
    "radius": 6.5,
    "fuse": 0,
    "throwSpeed": 12,
    "chargeTime": 0.5
  },
  {
    "id": "claymore",
    "name": "闊刀地雷",
    "slot": "lethal",
    "description": "定向地雷，由前方扇形範圍內的絆線觸發。",
    "count": 1,
    "unlockLevel": 13,
    "projectileKind": 10,
    "deployableKind": 0,
    "damage": 160,
    "radius": 4.5,
    "fuse": 0,
    "throwSpeed": 6,
    "chargeTime": 1.2
  },
  {
    "id": "proximity_mine",
    "name": "感應地雷",
    "slot": "lethal",
    "description": "壓力地雷，待發較慢，但涵蓋每個來向，不只一個扇面。",
    "count": 1,
    "unlockLevel": 16,
    "projectileKind": 10,
    "deployableKind": 1,
    "damage": 150,
    "radius": 4,
    "fuse": 0,
    "throwSpeed": 6,
    "chargeTime": 1.8
  },
  {
    "id": "thermite",
    "name": "鋁熱劑",
    "slot": "lethal",
    "description": "接觸即燃。爆炸威力低，但留在火裡的人會被燒死。",
    "count": 1,
    "unlockLevel": 19,
    "projectileKind": 3,
    "damage": 45,
    "radius": 2.5,
    "fuse": 0.5,
    "throwSpeed": 17,
    "effect": {
      "burn": 30,
      "duration": 5
    }
  },
  {
    "id": "molotov",
    "name": "汽油彈",
    "slot": "lethal",
    "description": "碎裂成一灘火。用途是封鎖區域，而非落點擊殺。",
    "count": 1,
    "unlockLevel": 22,
    "projectileKind": 2,
    "damage": 30,
    "radius": 3.2,
    "fuse": 0,
    "throwSpeed": 15,
    "effect": {
      "burn": 22,
      "duration": 8
    }
  },
  {
    "id": "flashbang",
    "name": "閃光彈",
    "slot": "tactical",
    "description": "任何朝它附近看的人都會目盲耳鳴。",
    "count": 2,
    "unlockLevel": 0,
    "projectileKind": 4,
    "radius": 8,
    "fuse": 1.6,
    "throwSpeed": 17,
    "effect": {
      "flash": 1,
      "duration": 4.5
    }
  },
  {
    "id": "stun_grenade",
    "name": "震撼彈",
    "slot": "tactical",
    "description": "震盪衝擊，拖慢移動與瞄準，但不奪走視線。",
    "count": 2,
    "unlockLevel": 3,
    "projectileKind": 5,
    "radius": 6.5,
    "fuse": 1.4,
    "throwSpeed": 17,
    "effect": {
      "stun": 1,
      "duration": 4
    }
  },
  {
    "id": "smoke_grenade",
    "name": "煙霧彈",
    "slot": "tactical",
    "description": "厚實煙幕，用來穿越空曠地或掩護安裝。",
    "count": 1,
    "unlockLevel": 6,
    "projectileKind": 6,
    "radius": 7,
    "fuse": 1,
    "throwSpeed": 16,
    "effect": {
      "smoke": 1,
      "duration": 15
    }
  },
  {
    "id": "snapshot_grenade",
    "name": "快照手榴彈",
    "slot": "tactical",
    "description": "對爆炸範圍內的所有人閃現一次線框輪廓。",
    "count": 2,
    "unlockLevel": 9,
    "projectileKind": 5,
    "radius": 12,
    "fuse": 1.2,
    "throwSpeed": 18,
    "effect": {
      "duration": 2.5
    }
  },
  {
    "id": "decoy_grenade",
    "name": "誘餌手榴彈",
    "slot": "tactical",
    "description": "偽造槍聲與雷達訊號，把注意力從你身上引開。",
    "count": 2,
    "unlockLevel": 12,
    "projectileKind": 4,
    "radius": 10,
    "fuse": 1,
    "throwSpeed": 17,
    "effect": {
      "duration": 8
    }
  },
  {
    "id": "gas_grenade",
    "name": "毒氣彈",
    "slot": "tactical",
    "description": "滯留的氣霧，模糊視線、拖慢移動、灼傷肺部。",
    "count": 1,
    "unlockLevel": 15,
    "projectileKind": 6,
    "radius": 6,
    "fuse": 1,
    "throwSpeed": 15,
    "effect": {
      "smoke": 0.6,
      "stun": 0.5,
      "burn": 8,
      "duration": 10
    }
  },
  {
    "id": "heartbeat_sensor",
    "name": "心跳感測器",
    "slot": "tactical",
    "description": "手持掃描器，探測附近的動靜。是拿在手上而非投擲——查看時無法開火。",
    "count": 1,
    "unlockLevel": 18,
    "radius": 25,
    "effect": {
      "duration": 0
    }
  },
  {
    "id": "dead_silence",
    "name": "死寂",
    "slot": "field",
    "description": "一段時間內腳步無聲，擊殺還能延長時間。",
    "count": 1,
    "unlockLevel": 5,
    "chargeTime": 60,
    "effect": {
      "duration": 15
    }
  },
  {
    "id": "deployable_cover",
    "name": "部署式掩體",
    "slot": "field",
    "description": "彈開式防彈盾板，在沒有掩體的地方造出掩體。",
    "count": 1,
    "unlockLevel": 2,
    "deployableKind": 5,
    "radius": 2,
    "chargeTime": 45,
    "effect": {
      "duration": 120
    }
  },
  {
    "id": "tactical_insertion",
    "name": "戰術插旗",
    "slot": "field",
    "description": "指定你重生位置的信號彈。敵人看得見，也能摧毀。",
    "count": 1,
    "unlockLevel": 8,
    "deployableKind": 3,
    "radius": 1,
    "chargeTime": 40,
    "effect": {
      "duration": 120
    }
  },
  {
    "id": "munitions_box",
    "name": "彈藥箱",
    "slot": "field",
    "description": "為走到它旁邊的隊友補充彈藥與裝備。",
    "count": 1,
    "unlockLevel": 11,
    "deployableKind": 6,
    "radius": 3,
    "chargeTime": 70,
    "effect": {
      "duration": 120
    }
  },
  {
    "id": "trophy_system",
    "name": "戰利品系統",
    "slot": "field",
    "description": "擊落接下來幾枚靠近它的手榴彈、火箭或無人機。",
    "count": 1,
    "unlockLevel": 14,
    "deployableKind": 4,
    "radius": 6,
    "chargeTime": 80,
    "effect": {
      "duration": 120
    }
  },
  {
    "id": "recon_drone",
    "name": "偵察無人機",
    "slot": "field",
    "description": "操控小型無人機，標記它看見的目標。操控期間你毫無防備。",
    "count": 1,
    "unlockLevel": 17,
    "radius": 40,
    "chargeTime": 90,
    "effect": {
      "duration": 25
    }
  },
  {
    "id": "stopping_power",
    "name": "停止力彈藥",
    "slot": "field",
    "description": "一個彈匣的高壓彈，讓大多數擊殺都少打一發。",
    "count": 1,
    "unlockLevel": 20,
    "chargeTime": 100,
    "effect": {
      "duration": 0
    }
  },
  {
    "id": "emp_drone",
    "name": "EMP無人機",
    "slot": "field",
    "description": "自殺式無人機，在爆炸範圍內燒毀敵方HUD與裝備。",
    "count": 1,
    "unlockLevel": 23,
    "damage": 60,
    "radius": 12,
    "chargeTime": 110,
    "effect": {
      "emp": 1,
      "duration": 8
    }
  }
]
""""";
}
