// <auto-generated />
namespace OperationVanguard.Core;

internal static partial class RegistryPayloads
{
    internal const string ModesJson = """""
[
  {
    "id": "tdm",
    "name": "團隊死鬥",
    "shortName": "團隊",
    "description": "兩支隊伍。擊殺數多的一方獲勝。沒別的好想。",
    "teamBased": true,
    "scoreLimit": 75,
    "timeLimit": 600,
    "roundsToWin": 1,
    "roundTime": 600,
    "respawn": true,
    "respawnDelay": 4,
    "objectiveKind": null,
    "scoring": {
      "kill": 100,
      "assist": 50,
      "capture": 200,
      "defend": 100,
      "objectiveTick": 0,
      "objectiveTickInterval": 1,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {},
    "killstreaksEnabled": true,
    "scorestreaksOnly": false,
    "teamScoresOnKill": true,
    "teamSize": [
      4,
      9
    ],
    "introLine": "殲滅敵方隊伍。"
  },
  {
    "id": "ffa",
    "name": "大混戰",
    "shortName": "混戰",
    "description": "所有人互為敵人。先達三十殺者獲勝。",
    "teamBased": false,
    "scoreLimit": 30,
    "timeLimit": 600,
    "roundsToWin": 1,
    "roundTime": 600,
    "respawn": true,
    "respawnDelay": 3,
    "objectiveKind": null,
    "scoring": {
      "kill": 100,
      "assist": 0,
      "capture": 200,
      "defend": 100,
      "objectiveTick": 0,
      "objectiveTickInterval": 1,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {},
    "killstreaksEnabled": true,
    "scorestreaksOnly": false,
    "teamScoresOnKill": true,
    "teamSize": [
      4,
      12
    ],
    "introLine": "各自為戰。"
  },
  {
    "id": "domination",
    "name": "據點爭奪",
    "shortName": "據點",
    "description": "佔領並守住三個據點。每持有一面旗幟就持續累積分數。",
    "teamBased": true,
    "scoreLimit": 200,
    "timeLimit": 900,
    "roundsToWin": 1,
    "roundTime": 900,
    "respawn": true,
    "respawnDelay": 5,
    "objectiveKind": "dom_flag",
    "scoring": {
      "kill": 100,
      "assist": 50,
      "capture": 200,
      "defend": 100,
      "objectiveTick": 1,
      "objectiveTickInterval": 5,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {
      "captureTime": 10,
      "captureSpeedPerExtraPlayer": 0.5,
      "captureDecayRate": 0.5,
      "contestedStopsCapture": true
    },
    "killstreaksEnabled": true,
    "scorestreaksOnly": false,
    "teamScoresOnKill": false,
    "teamSize": [
      4,
      12
    ],
    "introLine": "佔領並守住目標。"
  },
  {
    "id": "snd",
    "name": "搜索與摧毀",
    "shortName": "搜毀",
    "description": "每回合一條命。安裝炸彈，或阻止對方安裝。",
    "teamBased": true,
    "scoreLimit": 0,
    "timeLimit": 0,
    "roundsToWin": 6,
    "roundTime": 105,
    "respawn": false,
    "respawnDelay": 0,
    "objectiveKind": "bomb_site",
    "scoring": {
      "kill": 100,
      "assist": 50,
      "capture": 200,
      "defend": 100,
      "objectiveTick": 0,
      "objectiveTickInterval": 1,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {
      "bombTimer": 45,
      "plantTime": 5,
      "defuseTime": 7.5,
      "swapSidesAfterRound": 6,
      "prepTime": 5
    },
    "killstreaksEnabled": true,
    "scorestreaksOnly": true,
    "teamScoresOnKill": false,
    "teamSize": [
      4,
      6
    ],
    "introLine": "搜索與摧毀。只有一條命。"
  },
  {
    "id": "kc",
    "name": "擊殺確認",
    "shortName": "確認",
    "description": "撿到識別牌，擊殺才算數。別讓敵人撿走他們的。",
    "teamBased": true,
    "scoreLimit": 65,
    "timeLimit": 600,
    "roundsToWin": 1,
    "roundTime": 600,
    "respawn": true,
    "respawnDelay": 4,
    "objectiveKind": null,
    "scoring": {
      "kill": 50,
      "assist": 50,
      "capture": 200,
      "defend": 100,
      "objectiveTick": 0,
      "objectiveTickInterval": 1,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {
      "tagLifetime": 30,
      "tagPickupRadius": 1.6
    },
    "killstreaksEnabled": true,
    "scorestreaksOnly": false,
    "teamScoresOnKill": false,
    "teamSize": [
      4,
      9
    ],
    "introLine": "撿取識別牌。確認你的擊殺。"
  },
  {
    "id": "hardpoint",
    "name": "要塞",
    "shortName": "要塞",
    "description": "守住輪替的區域。每秒一分，每分鐘換位。",
    "teamBased": true,
    "scoreLimit": 250,
    "timeLimit": 600,
    "roundsToWin": 1,
    "roundTime": 600,
    "respawn": true,
    "respawnDelay": 5,
    "objectiveKind": "hardpoint",
    "scoring": {
      "kill": 100,
      "assist": 50,
      "capture": 100,
      "defend": 50,
      "objectiveTick": 1,
      "objectiveTickInterval": 1,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {
      "rotationTime": 60,
      "rotationGap": 5,
      "contestedStopsScoring": true
    },
    "killstreaksEnabled": true,
    "scorestreaksOnly": false,
    "teamScoresOnKill": false,
    "teamSize": [
      4,
      6
    ],
    "introLine": "拿下要塞。"
  },
  {
    "id": "hq",
    "name": "總部",
    "shortName": "總部",
    "description": "佔領總部。守住它——但持有期間無法重生。",
    "teamBased": true,
    "scoreLimit": 200,
    "timeLimit": 720,
    "roundsToWin": 1,
    "roundTime": 720,
    "respawn": true,
    "respawnDelay": 5,
    "objectiveKind": "hq",
    "scoring": {
      "kill": 100,
      "assist": 50,
      "capture": 250,
      "defend": 100,
      "objectiveTick": 5,
      "objectiveTickInterval": 5,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {
      "captureTime": 8,
      "holdTime": 60,
      "respawnGap": 8,
      "ownerRespawnDisabled": true
    },
    "killstreaksEnabled": true,
    "scorestreaksOnly": false,
    "teamScoresOnKill": false,
    "teamSize": [
      4,
      9
    ],
    "introLine": "拿下總部。"
  },
  {
    "id": "gungame",
    "name": "槍械競賽",
    "shortName": "槍賽",
    "description": "所有人從同一把槍開始。每次擊殺就升一級。走完整座階梯。",
    "teamBased": false,
    "scoreLimit": 0,
    "timeLimit": 900,
    "roundsToWin": 1,
    "roundTime": 900,
    "respawn": true,
    "respawnDelay": 2.5,
    "objectiveKind": null,
    "scoring": {
      "kill": 100,
      "assist": 0,
      "capture": 200,
      "defend": 100,
      "objectiveTick": 0,
      "objectiveTickInterval": 1,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {
      "meleeDemotes": true,
      "ladderLength": 20
    },
    "killstreaksEnabled": false,
    "scorestreaksOnly": false,
    "teamScoresOnKill": false,
    "teamSize": [
      4,
      12
    ],
    "introLine": "槍械競賽。一路往上爬。"
  },
  {
    "id": "zombies",
    "name": "殭屍",
    "shortName": "殭屍",
    "description": "活下去。牠們每回合都更快、更硬、更多。",
    "teamBased": true,
    "scoreLimit": 0,
    "timeLimit": 0,
    "roundsToWin": 0,
    "roundTime": 0,
    "respawn": true,
    "respawnDelay": 0,
    "objectiveKind": null,
    "scoring": {
      "kill": 60,
      "assist": 10,
      "capture": 200,
      "defend": 100,
      "objectiveTick": 0,
      "objectiveTickInterval": 1,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {
      "baseZombieCount": 6,
      "zombieCountGrowth": 1.18,
      "healthGrowth": 1.11,
      "speedGrowth": 1.035,
      "maxSpeedMultiplier": 1.9,
      "dropInterval": 4,
      "pointsPerHit": 10,
      "pointsPerKill": 60
    },
    "killstreaksEnabled": false,
    "scorestreaksOnly": false,
    "teamScoresOnKill": false,
    "teamSize": [
      1,
      4
    ],
    "introLine": "活下去。"
  },
  {
    "id": "campaign",
    "name": "戰役",
    "shortName": "戰役",
    "description": "六場任務。其中一場在你已經打過的屋頂上。",
    "teamBased": true,
    "scoreLimit": 0,
    "timeLimit": 0,
    "roundsToWin": 0,
    "roundTime": 0,
    "respawn": false,
    "respawnDelay": 0,
    "objectiveKind": null,
    "scoring": {
      "kill": 50,
      "assist": 25,
      "capture": 200,
      "defend": 100,
      "objectiveTick": 0,
      "objectiveTickInterval": 1,
      "plant": 250,
      "defuse": 250,
      "confirm": 50,
      "deny": 50
    },
    "params": {},
    "killstreaksEnabled": false,
    "scorestreaksOnly": false,
    "teamScoresOnKill": false,
    "teamSize": [
      1,
      1
    ],
    "introLine": "任務開始。"
  }
]
""""";
}
