/** Generate the exact C# registry payloads from the canonical web tables. */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ATTACHMENTS } from '../src/shared/data/attachments.js';
import { EQUIPMENT } from '../src/shared/data/equipment.js';
import { KILLSTREAKS } from '../src/shared/data/killstreaks.js';
import { GAME_MODES, MODE_IDS } from '../src/shared/data/modes.js';
import { PERKS } from '../src/shared/data/perks.js';
import { WEAPON_IDS, WEAPONS } from '../src/shared/data/weapons.js';

const here = dirname(fileURLToPath(import.meta.url));
const outputDirectory = resolve(here, '../../dotnet/src/OperationVanguard.Core/Data');
mkdirSync(outputDirectory, { recursive: true });

function replaceNonFinite(_key: string, value: unknown): unknown {
  if (value === Number.POSITIVE_INFINITY) return '__OV_INFINITY__';
  if (value === Number.NEGATIVE_INFINITY) return '__OV_NEG_INFINITY__';
  if (typeof value === 'number' && Number.isNaN(value)) return '__OV_NAN__';
  return value;
}

function emit(name: string, value: unknown): void {
  const json = JSON.stringify(value, replaceNonFinite, 2);
  const source = `// <auto-generated />
namespace OperationVanguard.Core;

internal static partial class RegistryPayloads
{
    internal const string ${name} = """""
${json}
""""";
}
`;
  writeFileSync(resolve(outputDirectory, `${name}.Generated.cs`), source, 'utf8');
}

emit('WeaponsJson', WEAPON_IDS.map((id) => WEAPONS[id]));
emit('AttachmentsJson', Object.values(ATTACHMENTS));
emit('PerksJson', Object.values(PERKS));
emit('EquipmentJson', Object.values(EQUIPMENT));
emit('KillstreaksJson', Object.values(KILLSTREAKS));
emit('ModesJson', MODE_IDS.map((id) => GAME_MODES[id]));

console.log(`Wrote C# registry payloads to ${outputDirectory}`);
