export const meta = {
  name: 'vanguard-core-data',
  description: 'Build the arsenal, loadout tables, collision backend, maps and mode rules for Operation Vanguard',
  phases: [
    { title: 'Build', detail: 'five independent subsystems written against the shared contracts' },
    { title: 'Review', detail: 'contract conformance + balance sanity, fixes applied in place' },
  ],
};

const CONTEXT = [
  'PROJECT: "Operation Vanguard" — a browser-native Call of Duty-style multiplayer FPS.',
  'Repo root: C:/src/operation-vanguard  (Windows, PowerShell; the web implementation lives under web/)',
  'Stack: TypeScript strict, Vite, Three.js (RENDER SIDE ONLY), Vitest. Node 24.',
  '',
  'HARD ARCHITECTURAL RULES — violating these breaks the build:',
  '1. Nothing under src/shared/ may import three.js. The shared simulation runs on the',
  '   Node server too. Only src/client/ may import three.',
  '2. Import paths inside src/shared use RELATIVE paths with an explicit .js extension',
  "   (e.g. import { clamp } from '../math.js'). Required by the bundler + node config.",
  '3. The simulation must be deterministic. Never call Math.random() in shared sim code —',
  "   use the seeded Rng class from '../rng.js'.",
  '4. TypeScript strict mode. tsc --noEmit must pass. No "any" unless truly unavoidable.',
  '5. Units are metres / seconds / radians throughout.',
  '',
  'CONTRACTS ALREADY WRITTEN — read these before you write a single line:',
  '  src/shared/math.ts                      Vec3 + angle + geometry helpers (allocation-free)',
  '  src/shared/constants.ts                 all movement/combat/scoring tuning values',
  '  src/shared/types.ts                     entities, input, events, WorldState, enums',
  '  src/shared/rng.ts                       seeded deterministic RNG',
  '  src/shared/data/weapon-types.ts         WeaponDef schema + damageAtRange/timeToKill helpers',
  '  src/shared/map/map-types.ts             MapDef brush format + authoring helpers',
  '  src/shared/collision/collision-types.ts CollisionWorld interface + surface tables',
  '',
  'CODE STYLE (match it — the reviewer will check):',
  '- Comments explain WHY, not WHAT. Dense at the top of a file explaining the design',
  '  decision; sparse inside functions. No comment restates the code.',
  '- Named exports only. No default exports.',
  '- Prefer plain data + pure functions over classes, except where mutable state is',
  '  genuinely the point (e.g. a spatial index).',
  '- No placeholder/TODO stubs. Everything you write must be complete and working.',
].join('\n');

const SPECS = [
  {
    key: 'weapons',
    label: 'arsenal',
    files: 'src/shared/data/weapons.ts',
    prompt: [
      'Write src/shared/data/weapons.ts — the complete Operation Vanguard arsenal.',
      '',
      'Export:',
      '  export const WEAPONS: Record<string, WeaponDef>',
      '  export function getWeapon(id: string): WeaponDef          // throws on unknown id',
      '  export function tryGetWeapon(id: string): WeaponDef | undefined',
      '  export const WEAPONS_BY_CLASS: Record<WeaponClass, WeaponDef[]>',
      '  export const DEFAULT_PRIMARY: string',
      '  export const DEFAULT_SECONDARY: string',
      '  export function validateArsenal(): string[]',
      '',
      'Build AT LEAST 32 weapons with distinct, memorable identities:',
      '  - 7 assault rifles (one 3-round burst, one high-damage slow-firing, one low-recoil',
      '    laser, one fast-firing low-damage, one bullpup, one battle rifle, one hybrid)',
      '  - 6 SMGs spanning a real speed/range tradeoff (one sub-1200rpm bullet hose that falls',
      '    off a cliff past 15m, one controllable AR-lite SMG, etc.)',
      '  - 4 LMGs (slow ADS, huge mags, strong penetration)',
      '  - 4 sniper rifles (one true one-shot-chest quickscoper with slow ADS, one semi-auto',
      '    needing two hits, one anti-materiel with extreme penetration, one lightweight)',
      '  - 3 marksman rifles (semi-auto, 2-3 shot kill, fast)',
      '  - 3 shotguns (pump one-shot-in-close, semi-auto, full-auto)',
      '  - 4 pistols (including a fast machine pistol and a hand-cannon)',
      '  - 3 launchers (dumbfire rocket, lock-on AA, grenade launcher)',
      '  - 2 melee (combat knife, riot shield — WeaponClass.Melee, huge meleeDamage,',
      '    heavy movementSpeedMultiplier penalty)',
      '',
      'BALANCE IS THE POINT. Design against these targets and verify each with the',
      'timeToKill() helper from weapon-types.ts BEFORE finalising numbers:',
      '  - AR time-to-kill at 20m: 250-400ms chest, meaningfully faster with headshots.',
      '  - SMG TTK inside 12m: 180-300ms. SMGs must LOSE to ARs past ~25m — express that',
      '    with a steep damage curve, not with spread alone.',
      '  - Sniper: the bolt-action one-shot-kills to chest inside its first damage stop and',
      '    to the head at any range; its adsTime must be >= 0.5s so it is not strictly better.',
      '  - Shotgun: lethal inside ~6m, useless past ~14m.',
      '  - No weapon may have a sub-150ms body-shot TTK at any range.',
      'Damage curves need >= 3 stops. Recoil patterns need >= 8 entries with real character —',
      'a pattern that rises, drifts one way, then snaps back is far better than pure vertical.',
      '',
      'Fill the audio{} and model{} blocks meaningfully per weapon — they drive PROCEDURAL',
      'synthesis and PROCEDURAL viewmodel construction (the game ships zero binary assets).',
      'A .50 cal must read as low bodyFreq / high boom / long tail; an SMG as high bodyFreq /',
      'short crackDuration.',
      '',
      'unlockLevel should spread sensibly across ranks 1-55.',
      '',
      'validateArsenal() returns a list of balance violations: the TTK bands above, mag sizes',
      '> 0, monotonically non-increasing damage curves, unique attachmentSlots entries, and',
      'non-empty recoil patterns. The test suite calls it and asserts the list is empty.',
    ].join('\n'),
  },
  {
    key: 'loadout',
    label: 'attachments+perks+streaks',
    files: 'src/shared/data/attachments.ts, src/shared/data/perks.ts, src/shared/data/killstreaks.ts, src/shared/data/equipment.ts',
    prompt: [
      'Write four files completing the loadout system. Do NOT touch weapons.ts — another',
      'agent owns it; only import types from weapon-types.ts.',
      '',
      '--- src/shared/data/attachments.ts ---',
      'An attachment is a sparse set of modifiers over WeaponDef fields, so applying them is',
      'one generic pass:',
      '',
      '  export interface StatModifier {',
      '    // multiplicative, 1 = no change',
      '    adsTime?: number; sprintOutTime?: number; drawTime?: number; reloadTime?: number;',
      '    movementSpeed?: number; adsSpeed?: number; recoilPitch?: number; recoilYaw?: number;',
      '    hipSpread?: number; adsSpread?: number; damageRangeScale?: number;',
      '    penetration?: number; muzzleVelocity?: number; swayAmount?: number;',
      '    // additive',
      '    magSizeAdd?: number; adsZoomAdd?: number;',
      '    // flags',
      '    suppressed?: boolean; hidesMinimapDot?: boolean;',
      '  }',
      '  export interface AttachmentDef {',
      '    id: string; name: string; slot: AttachmentSlot; description: string;',
      '    classes: WeaponClass[];   // empty = all',
      '    mods: StatModifier; unlockLevel: number;',
      '    pros: string[]; cons: string[];',
      '  }',
      '  export const ATTACHMENTS: Record<string, AttachmentDef>',
      '  export function attachmentsForSlot(slot: AttachmentSlot, weaponClass: WeaponClass): AttachmentDef[]',
      '  export function resolveWeapon(base: WeaponDef, attachmentIds: readonly string[]): WeaponDef',
      '',
      'resolveWeapon must deep-clone and apply every modifier, scaling damage-curve DISTANCES',
      '(not damage values) by damageRangeScale, and scaling each recoil pattern entry. Pure —',
      'never mutates the base def. Cap applied attachments at MAX_EQUIPPED_ATTACHMENTS and',
      'ignore duplicates in the same slot (first wins).',
      '',
      'Write 45+ attachments across all 8 slots. EVERY attachment must have a real downside —',
      'a suppressor costs damage range and ADS time; a 60-round mag costs reload and ADS.',
      'Never write a strictly-positive attachment.',
      '',
      '--- src/shared/data/perks.ts ---',
      'Three tiers, 8+ perks per tier, in the COD tradition, under original names: extra',
      'lethal, silent footsteps, invisible to UAV, flash immunity, faster reload, faster ADS',
      'out of sprint, ping enemies on kill, extra armour, faster regen, dead-man-s-trigger,',
      'cheaper killstreaks, scavenger, see enemy equipment, faster capture, etc.',
      '',
      '  export interface PerkDef {',
      '    id: string; name: string; tier: 1 | 2 | 3; description: string; icon: string;',
      '    unlockLevel: number; effects: PerkEffects;',
      '  }',
      '  export interface PerkEffects {',
      '    movementSpeedMult?: number; adsSpeedMult?: number; reloadSpeedMult?: number;',
      '    swapSpeedMult?: number; sprintOutMult?: number; healthRegenDelayMult?: number;',
      '    healthRegenRateMult?: number; extraLethal?: number; extraTactical?: number;',
      '    silentMovement?: boolean; hiddenFromUav?: boolean; flashImmune?: boolean;',
      '    explosiveResistMult?: number; fallDamageImmune?: boolean;',
      '    killstreakCostMult?: number; scavenger?: boolean; seeEnemyEquipment?: boolean;',
      '    markEnemiesOnKill?: number; extraArmor?: number; deadMansTrigger?: boolean;',
      '    fasterCapture?: number; longerBreathHold?: number; noNameplateFlicker?: boolean;',
      '    quieterFootsteps?: number; extraKillstreakSlot?: boolean;',
      '  }',
      '  export const PERKS: Record<string, PerkDef>',
      '  export function perksForTier(tier: 1 | 2 | 3): PerkDef[]',
      '  export function combinePerkEffects(perkIds: readonly string[]): ResolvedPerkEffects',
      '',
      'combinePerkEffects merges *Mult fields multiplicatively, count fields additively, and',
      'ORs booleans. It returns a FULLY populated object with neutral defaults so callers',
      'never null-check. Export the ResolvedPerkEffects type with all fields required.',
      '',
      '--- src/shared/data/killstreaks.ts ---',
      '  export interface KillstreakDef {',
      '    id: string; name: string; cost: number; scoreCost: number; description: string;',
      "    kind: 'passive' | 'call_in' | 'controlled' | 'care_package' | 'deployable';",
      '    duration: number; vehicle?: KillstreakVehicleKind;',
      '    damage?: number; radius?: number; health?: number; unlockLevel: number;',
      '    friendlyAnnounce: string; enemyAnnounce: string;',
      '  }',
      'Include at minimum: UAV(3), Counter-UAV(4), Care Package(4), Cluster Strike(5),',
      'Precision Airstrike(5), Sentry Gun(6), Cruise Missile(7), Attack Chopper(7),',
      'VTOL Jet(8), Chopper Gunner(9), Gunship(10), Juggernaut(12), Tactical Nuke(25 — ends',
      'the match). Costs must escalate coherently.',
      '  export const KILLSTREAKS: Record<string, KillstreakDef>',
      '  export const DEFAULT_KILLSTREAKS: string[]',
      '  export function getKillstreak(id: string): KillstreakDef',
      '',
      '--- src/shared/data/equipment.ts ---',
      'Lethal + tactical equipment: frag, semtex, throwing knife, C4, claymore, proximity',
      'mine, thermite, molotov / flashbang, stun, smoke, snapshot, decoy, gas, heartbeat',
      'sensor. Plus field upgrades: Dead Silence, Trophy System, Munitions Box, Deployable',
      'Cover, Stopping Power rounds, Tactical Insertion, Recon Drone, EMP Drone.',
      '',
      '  export interface EquipmentDef {',
      "    id: string; name: string; slot: 'lethal' | 'tactical' | 'field';",
      '    description: string; count: number; unlockLevel: number;',
      '    projectileKind?: ProjectileKind; deployableKind?: DeployableKind;',
      '    damage?: number; radius?: number; fuse?: number; throwSpeed?: number;',
      '    chargeTime?: number;',
      '    effect?: { flash?: number; stun?: number; smoke?: number; emp?: number;',
      '               burn?: number; duration?: number };',
      '  }',
      '  export const EQUIPMENT: Record<string, EquipmentDef>',
      "  export function equipmentForSlot(slot: 'lethal' | 'tactical' | 'field'): EquipmentDef[]",
      '  export function getEquipment(id: string): EquipmentDef',
      '',
      'Reuse ProjectileKind / DeployableKind from ../types.js — do not invent parallel enums.',
    ].join('\n'),
  },
  {
    key: 'collision',
    label: 'collision backend',
    files: 'src/shared/collision/brush-collision.ts',
    prompt: [
      'Write src/shared/collision/brush-collision.ts — the concrete CollisionWorld.',
      '',
      '  export class BrushCollisionWorld implements CollisionWorld',
      '',
      'Constructed from a MapDef brush list plus a live registry of dynamic entities:',
      '',
      '  export interface DynamicCollider {',
      '    id: EntityId; layer: CollisionLayer; position: Vec3;',
      "    kind: 'capsule' | 'box';",
      '    height: number; radius: number;   // capsule',
      '    size?: Vec3; yaw?: number;        // box',
      '    active: boolean;',
      '  }',
      '',
      '  constructor(brushes: readonly Brush[], bounds: { min: Vec3; max: Vec3 })',
      '  setDynamicColliders(colliders: readonly DynamicCollider[]): void',
      '',
      'DESIGN REQUIREMENTS:',
      '- Broadphase: a uniform spatial hash grid over XZ (cell ~4m) of brush indices, built',
      '  once in the constructor. Ray queries walk the grid with a 2D DDA — never test every',
      '  brush. This is the difference between 60fps and 12fps with 24 players firing.',
      '- Convert each Brush at construction into oriented boxes (OBB with yaw) or, for Ramp,',
      '  a box plus a slope plane. Precompute world AABBs for broadphase, keep the OBB exact.',
      '- Ramps: a capsule standing on a ramp must get the SLOPE NORMAL back from sweepCapsule,',
      '  not an axis-aligned one, or the movement controller cannot do slope handling.',
      '- Cylinders: exact ray-cylinder and capsule-cylinder tests, not box approximations —',
      '  players hide behind pillars and it has to feel right.',
      '- sweepCapsule: conservative advancement is fine but MUST terminate. Return the earliest',
      '  fraction across all candidates. On startedSolid, report fraction 0 and set the flag so',
      '  the caller depenetrates instead of teleporting.',
      '- resolvePenetration: iterative, max 4 passes, push out along the minimum-translation',
      '  axis. Must be stable when wedged in a corner (no oscillation).',
      '- raycastAll: sorted nearest-first, computing "thickness" per hit by finding the exit',
      '  point through the same brush — bullet penetration depends on it.',
      '- isVisible: early-out ray against Sight layers only.',
      '- groundHeightAt: downward ray, returns -Infinity on miss.',
      '- Respect QueryFilter.layers, ignoreEntities and entityPredicate everywhere.',
      '- ZERO allocation in the steady state. Preallocate private module-scope scratch vectors',
      '  (do NOT use the shared TMP_A..TMP_D from math.ts — they are not reentrancy-safe).',
      '  Every method writes into its out parameter.',
      '- Deterministic: iterate brushes in a stable order; never depend on Map/Set ordering',
      '  derived from floats.',
      '',
      'Also export, so the renderer and navmesh builder reuse the same conversion:',
      '  export interface BrushCollider { ... }   // your OBB / cylinder representation',
      '  export function brushToColliders(brush: Brush, index: number): BrushCollider[]',
      '',
      'Tight, readable, well-commented numeric code. This is the single most',
      'performance- and correctness-critical file in the movement stack.',
    ].join('\n'),
  },
  {
    key: 'maps',
    label: 'maps',
    files: 'src/shared/map/maps/*.ts and src/shared/map/index.ts',
    prompt: [
      'Author the map set for Operation Vanguard, plus the registry.',
      '',
      'Files you own:',
      '  src/shared/map/maps/crossfire.ts',
      '  src/shared/map/maps/refinery.ts',
      '  src/shared/map/maps/shipment-yard.ts',
      '  src/shared/map/maps/highrise.ts',
      '  src/shared/map/maps/dust-market.ts',
      '  src/shared/map/maps/subway.ts',
      '  src/shared/map/index.ts     (MAPS record, getMap, MAP_IDS, mapsForMode, validateMap)',
      '',
      'Each map file exports one MapDef built with the helpers in ../map-types.js',
      '(box, ramp, cylinder, room, wallWithDoor).',
      '',
      'THE DESIGN BRIEF — these must actually play well, not merely exist:',
      '- COD three-lane design: left flank, mid, right flank, with cross-connections every',
      '  20-25m so a player is never more than ~4 seconds from a decision point. Fill lanes[].',
      '- Sightlines must be BROKEN. No lane runs the full map unobstructed; the longest clear',
      '  infantry sightline stays under ~45m.',
      '- Verticality on at least three maps: catwalks, second floors, a rooftop. Every raised',
      '  position needs two ways up and one way down.',
      "- Spawns: >= 16 per team per map, in named groups keyed to map halves and objectives",
      "  ('allies_home', 'allies_mid', 'contested_a', ...). Face them toward the action,",
      '  never into a wall.',
      '- Objectives: 3 Domination flags (A/B/C, B contested in the middle), 2 bomb sites,',
      '  4-5 Hardpoint zones whose rotation walks around the map (use the order field), HQ zones.',
      '- coverPoints: >= 30 per map with honest exposure values, placed where a defender would',
      '  actually hold. Bots use these — a lazy pass here makes the AI look stupid.',
      '- navLinks: mantles onto crates and catwalks, drop-downs off ledges.',
      '- Bounds must fully contain the geometry with a few metres of margin.',
      '- Lighting/ambience must give each map a distinct read: Crossfire = overcast European',
      '  village; Refinery = night industrial with sodium lamps; Shipment-Yard = a tiny',
      '  chaotic 22x22m container meat grinder; Highrise = bright rooftop, strong sun, long',
      '  shadows; Dust-Market = harsh desert noon; Subway = cramped fluorescent interior with',
      '  a long platform.',
      '',
      'SIZE GUIDE: Shipment-Yard ~22x22m; everything else 70-110m across. 120-320 brushes per',
      'map — enough that the space feels built, not blocked out. Build real structures with',
      'interiors you can enter and fight through, not scattered cubes.',
      '',
      'Keep the geometry READABLE: group brushes under section comments',
      '(// --- north warehouse ---) and use file-local helper functions for repeated',
      'structures (e.g. a shippingContainer(pos, yaw) helper).',
      '',
      'index.ts must also export:',
      '  export function validateMap(map: MapDef): string[]',
      'checking: bounds contain all brushes; every spawn is inside bounds and not inside a',
      'solid brush (AABB approximation is fine); objective labels are unique; lanes have >= 2',
      'waypoints; at least one spawn exists per team.',
    ].join('\n'),
  },
  {
    key: 'modes',
    label: 'game modes',
    files: 'src/shared/data/modes.ts',
    prompt: [
      'Write src/shared/data/modes.ts — declarative rules for every game mode.',
      '',
      'The goal: the match-flow engine written later is one generic loop driven by this data',
      'plus a small per-mode hook interface, not a switch statement with eight arms.',
      '',
      '  export interface GameModeDef {',
      '    id: string; name: string; shortName: string; description: string;',
      '    teamBased: boolean;',
      '    scoreLimit: number;      // 0 = time-limited only',
      '    timeLimit: number;       // seconds',
      '    roundsToWin: number;     // 1 for non-round modes',
      '    roundTime: number;',
      '    respawn: boolean; respawnDelay: number;',
      '    objectiveKind: ObjectiveKind | null;',
      '    scoring: {',
      '      kill: number; assist: number; capture: number; defend: number;',
      '      objectiveTick: number; objectiveTickInterval: number;',
      '      plant: number; defuse: number; confirm: number; deny: number;',
      '    };',
      '    params: Record<string, number | boolean | string>;',
      '    killstreaksEnabled: boolean; scorestreaksOnly: boolean;',
      '    teamSize: [number, number];',
      '    introLine: string;',
      '  }',
      '',
      'Define: Team Deathmatch, Free-For-All, Domination, Search & Destroy, Kill Confirmed,',
      'Hardpoint, Headquarters, Gun Game, Zombies (survival, Team.Hostile enemies, no score',
      'limit, infinite rounds).',
      '',
      'Get the details RIGHT — these are rules people know:',
      '- Domination: 3 flags, 1 point per flag per 5s tick, 200 to win, capture ~10s scaled by',
      '  number of players on the point, contested flags stop ticking.',
      '- Search & Destroy: no respawn, 6 rounds to win, 1m45s rounds, bomb 45s fuse, plant 5s,',
      '  defuse 7.5s, defenders win on timer, attackers win on detonation, sides swap at half.',
      '- Hardpoint: zone rotates every 60s, 1 point per second held, 250 to win, contested',
      '  pauses scoring.',
      '- Kill Confirmed: tags must be collected, 65 confirms to win, denying an enemy tag scores.',
      '- Headquarters: single zone; the capturing team cannot respawn while holding it; the',
      '  zone relocates after 60s of ownership.',
      '- Gun Game: FFA, everyone starts on the same weapon, advance one weapon per kill, a',
      '  melee kill demotes the victim one level, first to finish the ladder wins.',
      '',
      'Also export:',
      '  export const GAME_MODES: Record<string, GameModeDef>',
      '  export function getMode(id: string): GameModeDef',
      '  export const MODE_IDS: string[]',
      '  export function gunGameLadder(): string[]',
      '  export function defaultTeamSizeFor(mode: GameModeDef, playerCount: number): number',
      '',
      'IMPORTANT: another agent is writing the arsenal in parallel and you must not guess its',
      'weapon ids. Express the Gun Game ladder as a list of WeaponClass-based preferences plus',
      'a resolver that picks concrete ids at runtime from WEAPONS_BY_CLASS, so it can never',
      'reference a weapon that does not exist. Import WEAPONS_BY_CLASS lazily inside the',
      'resolver function body to avoid a module cycle.',
    ].join('\n'),
  },
];

// The original workflow was authored when the browser implementation occupied
// the repository root. Keep its readable source-relative briefs above, but root
// every actionable path in web/ before dispatching an agent.
const ROOTED_SPECS = SPECS.map((spec) => ({
  ...spec,
  files: spec.files.replaceAll('src/', 'web/src/'),
  prompt: spec.prompt.replaceAll('src/', 'web/src/'),
}));

phase('Build');

const results = await pipeline(
  ROOTED_SPECS,
  (spec) =>
    agent(
      CONTEXT +
        '\n\nYOUR TASK — you exclusively own: ' +
        spec.files +
        '\nDo not create or edit any other file.\n\n' +
        spec.prompt +
        '\n\nWhen done run: npm --prefix web run typecheck and fix any error attributable to' +
        " YOUR files. Errors in other agents' files are expected and not yours to fix." +
        '\nReport a one-paragraph summary of what you built and any balance decisions you made.',
      { label: 'build:' + spec.key, phase: 'Build' },
    ),
  (buildResult, spec) =>
    agent(
      CONTEXT +
        '\n\nYou are reviewing and FIXING the work another agent just did on: ' +
        spec.files +
        '\n\nTheir summary:\n' +
        (buildResult || '(no summary — the build may have failed; investigate)') +
        '\n\nDo this in order:' +
        '\n1. Read every file they own and check it against the contracts above. Type errors,' +
        ' wrong import paths (must be relative with .js), any three.js import under src/shared,' +
        ' or Math.random() in sim code are hard failures — fix them.' +
        '\n2. Hunt for PLACEHOLDER work: empty arrays where content was requested, stub' +
        ' functions, "TODO", copy-paste entries differing only in name, or counts below what' +
        ' the brief demanded. If you find any, WRITE THE MISSING CONTENT yourself.' +
        '\n3. Sanity-check the domain logic. Weapons: actually compute timeToKill() for several' +
        ' guns at 10m/25m/40m and confirm the bands hold. Maps: confirm spawn counts, that no' +
        ' spawn sits inside a brush, and brush counts meet the brief. Collision: trace' +
        ' sweepCapsule and confirm it cannot return fraction > 1 or loop forever. Attachments:' +
        ' confirm no attachment is strictly positive. Modes: confirm the numbers match the' +
        ' well-known rules.' +
        '\n4. Run: npm --prefix web run typecheck — fix every error in YOUR files.' +
        '\n\nApply fixes directly with Edit/Write. Report what was wrong, what you fixed, and' +
        ' anything still outstanding. Be blunt — do not report success if the work is thin.',
      { label: 'review:' + spec.key, phase: 'Review' },
    ),
);

return {
  built: ROOTED_SPECS.map((s) => s.key),
  reviews: results.map((r, i) => ({ key: ROOTED_SPECS[i].key, report: r })),
};
